[package]
name = "svdocgen"
version = "0.1.0"
authors = ["Igor Lesik <curoles@yahoo.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svgbobdoc = "0.2"
